<%@ Page Title="User Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="User.aspx.cs" Inherits="NHibernateExample.UI.WebForm._User" %>

<asp:Content ID="UserContent" ContentPlaceHolderID="MainContent" runat="server">
    
    <h1 style="padding-top:2em;"> User Page  </h1>
    <div class="form-group">
        <div class="row" style="padding-top:2em;">   
            <div class="col-lg-3" >   
                <label>Id</label>
                <asp:TextBox ID="txbId" runat="server" CssClass="form-control" ReadOnly="true"></asp:TextBox>
            </div>
            <div class="col-lg-3">   
                <label>First Name</label>
                <asp:TextBox ID="txbFirstName" runat="server" CssClass="form-control"></asp:TextBox>
            </div>
            <div class="col-lg-3">   
                <label>Last Name</label>
                <asp:TextBox ID="txbLastName" runat="server" CssClass="form-control"></asp:TextBox>
            </div>
            <div class="col-lg-3">   
                <label>Age</label>
                <asp:TextBox ID="txbAge" runat="server" CssClass="form-control" TextMode="Number"></asp:TextBox>
            </div>
            
        </div> 
        <div class="row" style="padding-top:2em;">   
            <div class="col-lg-12">   
                <asp:Button ID="btnSave" runat="server" Text="Save" OnClick="btnSave_Click"  CssClass="btn btn-success"/>
            </div>
            <div class="col-lg-12" style="padding-top:2em;">   
                <asp:GridView runat="server" ID="grdUsers" CssClass="table table-bordered" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="grdUsers_RowEditing" OnRowDeleting="grdUsers_RowDeleting"></asp:GridView>
            </div>
        </div> 
    </div>
    
</asp:Content>
